# Generated by Django 4.0 on 2022-01-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_teacher_remove_class_teacher_alter_class_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.style')),
                ('teachers', models.ManyToManyField(related_name='classes', to='classes.Teacher')),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
