# Generated by Django 4.0 on 2022-01-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_danceclass_delete_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceclass',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUES', 'Tuesday'), ('WED', 'Wednesday'), ('THURS', 'Thursday')], default=None, max_length=5),
        ),
    ]
