# Generated by Django 4.0 on 2022-01-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_danceclass_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='day',
            field=models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUES', 'Tuesday'), ('WED', 'Wednesday'), ('THURS', 'Thursday')], max_length=5, null=True),
        ),
    ]
